---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mock-frontend:latest  # Replace with actual image when available
        ports:
        - containerPort: 80
        env:
        - name: SERVER_URL
          value: "http://server:3000"  # This uses the internal DNS name of the server service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer  # This exposes the service externally