apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - postgres.yaml
  - namespace.yaml
namespace: hxckr-dev
patches:
  - path: server-patch.yaml
configMapGenerator:
  - name: rabbitmq-definitions
    files:
      - definitions.json