---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: git-service
  template:
    metadata:
      labels:
        app: git-service
    spec:
      initContainers:
      - name: wait-for-ssh-key-secret
        image: bitnami/kubectl:latest
        command: ['sh', '-c', 'until kubectl get secret ssh-key-secret; do echo "waiting for ssh-key-secret"; sleep 2; done']
      containers:
      - name: git-service
        image: extheoisah/hxckr-git-service:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SOFTSERVE_HOST
          value: "softserve"  # This uses the internal DNS name of the Softserve service
        - name: SOFTSERVE_PORT
          value: "3002"
        - name: SOFT_SERVE_INITIAL_ADMIN_KEYS
          valueFrom:
            secretKeyRef:
              name: ssh-key-secret
              key: id_rsa
---
apiVersion: v1
kind: Service
metadata:
  name: git-service
spec:
  selector:
    app: git-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP  # Internal service, not exposed externally