---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-queue
  template:
    metadata:
      labels:
        app: job-queue
    spec:
      containers:
      - name: job-queue
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: job-queue
spec:
  selector:
    app: job-queue
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: management