---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: extheoisah/hxckr-core:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: GIT_SERVICE_URL
          value: "http://git-service:8080"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@job-queue:5672"
        - name: RABBITMQ_QUEUE_NAME
          value: "backend_core_queue"
        # Database environment variable is now managed in the overlay patches for production and development
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP  # This is the default, but we're making it explicit