---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: softserve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: softserve
  template:
    metadata:
      labels:
        app: softserve
    spec:
      containers:
      - name: softserve
        image: mock-softserve:latest  # TODO:Replace with actual image when available
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: softserve
spec:
  selector:
    app: softserve
  ports:
  - port: 3002
    targetPort: 3002
  type: LoadBalancer  # This exposes the service externally