---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-test-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javascript-test-runner
  template:
    metadata:
      labels:
        app: javascript-test-runner
    spec:
      containers:
      - name: javascript-test-runner
        image: mock-javascript-test-runner:latest  # TODO: Replace with actual image when available
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: javascript-test-runner
spec:
  selector:
    app: javascript-test-runner
  ports:
  - port: 3004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-test-runner
  template:
    metadata:
      labels:
        app: python-test-runner
    spec:
      containers:
      - name: python-test-runner
        image: mock-python-test-runner:latest  # TODO: Replace with actual image when available
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: python-test-runner
spec:
  selector:
    app: python-test-runner
  ports:
  - port: 3005