---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-handler
  template:
    metadata:
      labels:
        app: webhook-handler
    spec:
      containers:
      - name: webhook-handler
        image: extheoisah/hxckr-webhook-handler:main
        ports:
        - containerPort: 3003
        env:
        - name: CORE_SERVICE_URL
          value: "http://server:4925"
        - name: PORT
          value: "3003"
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-handler
spec:
  selector:
    app: webhook-handler
  ports:
  - port: 3003